global:
  prefix: es
  interval: 1m
  timeout: 10
  jitter: 10
  black_re:
    - '^es_test_re'

aes_cluster:
  level: info
  interval: disable
  request_param:
    timeout: 10s

aes_node:
  black_re:
    - '^es_node_cache'
    - '^es_node_tx'
    - '^es_node_rx'
  request_param:
    timeout: 10s

indices:
  request_para,:
    timeout: 10s

ametrics:
  - name: line_type_connection_cnt
    index: sip_log_index*
    doc: line type connection cnt by line
    timeout: 10
    metric: es_{index}_{name}
    query_json: |
      {
        "size": 0,
        "query": {
          "bool":{
            "must_not":[
            {
              "match_phrase":{
                "connection_time":{
                  "query":"0"
                }
              }
            }
            ],
            "filter": {
              "bool": {
                "must": [
                { "range": { "@timestamp": { "gte": "now-5m", "lt": "now" } } }
                ]
              }
            }
          }
        },
        "aggs":{
          "line_type":{
            "terms":{
              "field":"line_type.keyword",
              "size":10,
              "order":{
                "_key":"desc"
              },
              "min_doc_count":1
            },
            "aggs": {
              "app_id":{
                "terms":{
                    "field":"app_id.keyword",
                    "size":10,
                    "order":{
                        "_key":"desc"
                    },
                    "min_doc_count":1
                },
                "aggs": {
                    "server_name":{
                        "terms":{
                            "field":"server_name.keyword",
                            "size":30,
                            "order":{
                                "_key":"desc"
                            },
                            "min_doc_count":1
                        }
                    }
                }
              }
            }
          }
        }
      }

  - name: server_connect_cnt
    index: sip_log_index*
    doc: server connection cnt by line
    metric: es_{index}_{name}
    query_json: |
      {
          "size": 0,
          "query": {
              "bool":{
                  "filter": {
                    "bool": {
                      "must": [
                        { "range": { "@timestamp": { "gte": "now-5m", "lt": "now" } } }
                      ]
                    }
                  }
              }
          },
          "aggs":{
              "server_name":{
                  "terms":{
                      "field":"server_name.keyword",
                      "size":30,
                      "order":{
                          "_key":"desc"
                      },
                      "min_doc_count":1
                  }
              }
          }
      }